definitions:
  handlers.InputPattern:
    properties:
      seq:
        items:
          type: integer
        type: array
    type: object
info:
  contact: {}
paths:
  /books:
    get:
      responses: {}
      summary: Get all books
      tags:
      - Books
    post:
      responses: {}
      summary: Create a new book
      tags:
      - Books
  /books/{id}:
    delete:
      responses: {}
      summary: Delete a book
      tags:
      - Books
    get:
      responses: {}
      summary: Get a book by ID
      tags:
      - Books
    put:
      responses: {}
      summary: Update a book
      tags:
      - Books
  /ingredients:
    get:
      responses: {}
      summary: Get all ingredients
      tags:
      - Ingredient
    post:
      responses: {}
      summary: Create a new ingredient
      tags:
      - Ingredient
  /ingredients/{id}:
    delete:
      responses: {}
      summary: Delete a ingredient
      tags:
      - Ingredient
    get:
      responses: {}
      summary: Get a ingredient by ID
      tags:
      - Ingredient
    put:
      responses: {}
      summary: Update a ingredient
      tags:
      - Ingredient
  /pattern:
    post:
      consumes:
      - application/json
      description: Detect the type of sequence and return the next number
      parameters:
      - description: Sequence input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.InputPattern'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Post pattern
      tags:
      - Pattern
  /productIngredients:
    get:
      responses: {}
      summary: Get all productIngredients
      tags:
      - Product Ingredient
    post:
      responses: {}
      summary: Create a new productIngredient
      tags:
      - Product Ingredient
  /productIngredients/{id}:
    delete:
      responses: {}
      summary: Delete a productIngredient
      tags:
      - Product Ingredient
    get:
      responses: {}
      summary: Get a productIngredient by ID
      tags:
      - Product Ingredient
    put:
      responses: {}
      summary: Update a productIngredient
      tags:
      - Product Ingredient
  /productIngredients/product/{productId}:
    get:
      responses: {}
      summary: Get a productIngredient by productID
      tags:
      - Product Ingredient
  /products:
    get:
      responses: {}
      summary: Get all products
      tags:
      - Product
    post:
      responses: {}
      summary: Create a new product
      tags:
      - Product
  /products/{id}:
    delete:
      responses: {}
      summary: Delete a product
      tags:
      - Product
    get:
      responses: {}
      summary: Get a product by ID
      tags:
      - Product
    put:
      responses: {}
      summary: Update a product
      tags:
      - Product
swagger: "2.0"
